[audio]
# input_port = { name = "xyz" }
# output_port = "none"
sample_rate = 44100
frames = 64

[midi]


[[midi.output_virtual_ports]]
name = "metronome"
sync_delay_ms = 0

[metronome]
enabled = true
# port = { name = "IAC Driver Bus 1" }
port = "default"
# bar_note = { key = 72 }
# beat_note = { channel = 0, key = 65, velocity = 100 }
